### ISSUE TITLE
Electron prebuilt (ABI 69) not loading on Windows 7 because of VCRUNTIME140.dll

### ISSUE THREAD

**Issue by jmeinke** [holepunchto/sodium-native#100]
We're using the sodium-native prebuilt binaries with Electron 4.1.5.
When starting our app on Windows 10 there are no problems. Starting the app on Windows 7 (32bit) however does not work until Visual C++ Redistributable for Visual Studio 2015 is installed.

On a fresh Windows 7 install, there is no VCRUNTIME140.dll. Can the binaries be built without linking to the runtime redistributable? Thanks!

**Comment by emilbayes** [comment]
Is this only when running `sodium-native` in electron or also with node? I don't know that they can. We use the default libsodium build and the default node-gyp options. Do you have more info on that aspect?

**Comment by emilbayes** [comment]
So the dependency is from libsodium. You can however create a custom NSIS script to install this for you as part of your app installation https://www.electron.build/configuration/nsis#custom-nsis-script
![image](https://user-images.githubusercontent.com/416524/58242504-39f8b600-7d4f-11e9-8397-7139ef4b293d.png)

**Comment by emilbayes** [comment]
@jedisct1 Can the above functions be linked into libsodium statically somehow?

**Comment by jedisct1** [comment]
I have no idea :/

**Comment by jmeinke** [comment]
We have bundled vcruntime140.dll with our electron app now, however, when the app is called from another app using a different working directory, we need to instruct our user to install the MSVS C++ 2015 Redistributable. This is not a big issue for us. It could still be a good idea to link the runtime statically.

**Comment by mafintosh** [comment]
@jmeinke how big is the dll?

**Comment by jmeinke** [comment]
@mafintosh 85.3 kB.

**Comment by emilbayes** [comment]
The static linking would need to happen in the libsodium layer tho, not in our bindings. We just load libsodium as a dynamic library

**Comment by mafintosh** [comment]
@emilbayes i think we could just vendor the 80kb dll. If it’s next to the prebuilt it should just work 🤞

**Comment by emilbayes** [comment]
This should now be solved for newer versions of electron supporting N-API

**Comment by mixmix** [comment]
I am seeing something similar to this with electron@12
On a clean windows 10 install  (using [Windows Sandbox](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview))

Installing [visual c++ redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=52685) is one way to fix it, though this is terrible UX for the average person installing an application D:

Specifically: 
- we try installing our electron app, then running it from Powershell
- we see an error about not being able to find `\\?\C:\Users\MyUserName\AppData\Local\Programs\MyAppName\resources\app.asar.unpacked\node_modules\sodium-native\prebuilds\win32-x64\node.napi.node`
    - _this appears to be a red herring - this file exists and the solution doesn't seem to touch this file_
    - NOTE : `\\?\` is valid syntax - it's a windows prefix which helps with opening file paths that are > 260 characters in length
- we inspect using Dependancies : https://github.com/lucasg/Dependencies
    - open `C:\Users\MyUserName\AppData\Local\Programs\MyAppName\resources\app.asar.unpacked\node_modules\sodium-native\prebuilds\win32-x64\libsodium.dll`
    - we see it reporting `VCRUNTIME140.dll` is missing
- after we install the above visual c+ redistributable, 
    - if we restart Dependancies, and load that file in we see everything is fine
    - our electron app now happily starts with none of those earlier errors

**Comment by vladimiry** [comment]
> terrible UX for the average person
> we try installing our electron app

You can just embed the Visual C++ Redistributable installing step into the electron-based app installer. The installer will test if there is a need to install the VC thing and do the stuff if needed. See here the ready-made NSIS script https://github.com/vladimiry/ElectronMail/blob/4104ef5bfe4dc613c68f3aef67264d67394475cb/scripts/electron-builder/installer.nsh which you can attach to the electron-builder's config https://github.com/vladimiry/ElectronMail/blob/dae8971316a191692f37dfb80f076298775aa8e7/electron-builder.yml#L80.

**Comment by mixmix** [comment]
@vladimiry you are a saint, thank you so much 🙏  (it works PERFECTLY)
I was dreading having to carefully craft something like that and then laboriously test that.

Here's a small gift in return which will save couple of megabytes 🎁 :

```
// electron-builder.config.js
  files: [
    // ....

    // sodium-native: only include needed prebuilds
    '!node_modules/sodium-native/{src,test,libsodium,tmp}',
    '!node_modules/sodium-native/prebuilds/*',
    'node_modules/sodium-native/prebuilds/${platform}-${arch}/*'
  ] 
```

**Comment by vladimiry** [comment]
Glad it helped with your need. I was subscribed to this issue so noticed the update and was able to put the comment.

> Here's a small gift in return which will save couple of megabytes gift :+1: 

I don't use prebuilds at all and so clean them all explicitly for all native modules, https://github.com/vladimiry/ElectronMail/blob/f3def9ca4989409f8f308a62468cf604caad07a6/package.json#L61-L65.
