### ISSUE TITLE
Failing to load In Electron 5/6

### ISSUE THREAD

**Issue by sentivate** [holepunchto/sodium-native#106]
The following error is given in terminal.

/sodium-native/prebuilds/darwin-x64/electron-73.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing

We have done a few rebuilds the issue is running inside electron. This issue doesn't seem to be present when just from node. Seems to also be present in Electron 5 as well.

Will put a bounty to have this resolved. Contact us if you can.

**Comment by vladimiry** [comment]
I did not face an issues with Electron 5/6. I was not using the prebuilds though like you do.

**Comment by sentivate** [comment]
@vladimiry Did you build from source as we tried that and still we got the same error except with a different number. Did you rebuild using an electron specific module?

**Comment by sentivate** [comment]
@vladimiry We have it working via building with electron-rebuild from source. However, we would like it so that the pre-builds work for those who don't know how to build native modules for electron from source. Especially if it needs to be compiled on multiple platforms.

**Comment by emilbayes** [comment]
I have also added electron to our CITGM script so we can monitor failures: https://github.com/sodium-friends/sodium-native-citgm/pull/1 (I want it see come to green before merging)

**Comment by emilbayes** [comment]
Everything is green now on CITGM, so closing this :)
