### ISSUE TITLE
2.4.4 install fails on node 10

### ISSUE THREAD

**Issue by dlongley** [holepunchto/sodium-native#107]
The 2.4.4 install is failing on node 10. Looks like `node-gyp-build` was removed from the `dependencies` (and moved to `devDependencies`) in `package.json` but it's still needed by the `install` script:

https://github.com/sodium-friends/sodium-native/commit/6820c935c34270dc78d236274e23d76c1489c160

`"install": "node-gyp-build \"node preinstall.js\" \"node postinstall.js\"",`

**Comment by mafintosh** [comment]
Sorry my bad. Fixed in 2.4.5
