### ISSUE TITLE
Cannot assign secure buffers created with `sodium.sodium_malloc()` as properties of objects

### ISSUE THREAD

**Issue by ameba23** [holepunchto/sodium-native#109]
I realise this is almost definately a feature and not a bug.  I am asking a question here, not reporting a bug.

Buffers created with `sodium.sodium_malloc()` have the property `secure: true` and some limitations what you can do with them, for example they cannot be assigned as properties of objects.  I assume this is to ensure they cannot be modified. 

We noticed that some projects using `sodium-native` get around this by just not using `sodium_malloc` - eg:  [`hypercore-crypto`uses `allocUnsafe`](https://github.com/mafintosh/hypercore-crypto/blob/09b09cfc80f6e0aa51e1dee1bab6e948ca5c6a60/index.js#L4) . 

So we are wondering what is the security tradeoff of using / not using 'secure buffers'. Is it only to do with not allowing them to be modified by the process elsewhere, or is it also related to 'zeroing them out' when the process finishes.

Thanks!

cc: @kyphae @emilbayes

**Comment by emilbayes** [comment]
You can assign secure buffers as properties to objects, without any security issues :)

Details on secure buffers are here: https://download.libsodium.org/doc/memory_management#guarded-heap-allocations

So I added that property so you can check if something is a secure buffer. It's of course not a bullet proof check, but gives indication if you're consuming from somewhere else. `Buffer.allocUnsafe` is completely different, and I wouldn't use that one anymore, as you can "escape" to other Buffers in the same pool by accessing the `buffer.buffer` property and getting to the ArrayBuffer, which might be a larger slab of memory shared by other Buffers elsewhere in the program.

secure buffers are not a general purpose slot in for normal buffers. They behave the same to the programmer, but have extra security features such as no swapping, memory locking, canary pages and such. That means they consume more memory than the size you ask for. I always use them for sensitive information such as private keys, symmetric keys, passwords and such, while normal buffers can be used for hash digests, public keys, cipher text and MACs.

One thing to be aware of is instance methods that return normal Buffers. eg. calling `Buffer.from` on a secure buffer, will copy to a normal one. Other methods also copy the memory and yield a normal buffer.

**Comment by ameba23** [comment]
thanks for the response! looks like we definately want secure buffers.

i think the confusion is coming from the following.  if i do this:
```
const sodium = require('sodium-native')
var buf = sodium.sodium_malloc(32)
sodium.randombytes_buf(buf, 32)
var anObject = { buf }
console.log(anObject.buf)
```
no problem, works as expected.
but if i do:
```
console.log(anObject)
```
i get:
```
internal/util/inspect.js:1365
  const indentation = ' '.repeat(ctx.indentationLvl);
                          ^

RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at reduceToSingleString (internal/util/inspect.js:1365:27)
    at formatRaw (internal/util/inspect.js:791:15)
    at formatValue (internal/util/inspect.js:529:10)
    at inspect (internal/util/inspect.js:187:10)
    at formatWithOptions (internal/util/inspect.js:1408:12)
    at Console.(anonymous function) (internal/console/constructor.js:277:10)
    at Console.log (internal/console/constructor.js:287:61)
    at Object.<anonymous> (/home/susi/Dokumente/sodtest/sodtest.js:6:9)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
```

which lead us to think that the problem was to do with assigning the buffer to an object.  but i guess its more to do with displaying that object.  Which is not so much of a problem.

**Comment by emilbayes** [comment]
I've seen that error on latest Node, but haven't had time to dig in. It comes from the Node core console.log logic

**Comment by ameba23** [comment]
that's good news.  so the problem is only cosmetic, and we can go ahead and use secure buffers!  nice one!

**Comment by emilbayes** [comment]
One trick I use to encapsulate secure buffers, unless you want to pass them around raw, is to keep their reference in a WeakMap. Here's a little example of a secret key encryption module that does that (notice the use in the constructor). Having this in a commonjs module means `priv` is inaccessible to other modules, and being a weak map, the key is tied to the lifetime of the instance:

```js
const sodium = require('sodium-native')
const assert = require('nanoassert')
const priv = new WeakMap()

class Key {
  static BYTES = sodium.crypto_secretbox_KEYBYTES
  static NONCEBYTES = crypto.crypto_aead_xchacha20poly1305_ietf_NPUBBYTES
  static TAGBYTES = sodium.crypto_aead_xchacha20poly1305_ietf_ABYTES

  static create () {
    const key = sodium.sodium_malloc(this.BYTES)
    sodium.randombytes_buf(key)

    return new this(key)
  }

  static import (key) {
    return new this(key)
  }

  constructor (key) {
    assert(key.byteLength === this.BYTES, 'key must be Key.BYTES long')
    assert(key.secure, 'key must be secure buffer')

    this.destroyed = false
    priv.set(this, key)
  }

  encrypt (plaintext, buf) {
    if (this.destroyed) throw new Error('Destroyed')

    assert(Buffer.isBuffer(plaintext), 'plaintext must be (secure) buffer')
    const outlen = this.encryptLength(plaintext)
    if (buf == null) buf = Buffer.alloc(outlen)
    assert(buf.byteLength === outlen, 'buf must be encryptLength(plaintext) long')

    const nonce = buf.subarray(0, Key.NONCEBYTES)
    const ciphertext = buf.subarray(Key.NONCEBYTES)

    sodium.randombytes_buf(nonce)
    sodium.crypto_aead_xchacha20poly1305_ietf_encrypt(ciphertext, plaintext, null, null, nonce, priv.get(this))

    return buf
  }

  encryptLength (plaintext) {
    assert(Buffer.isBuffer(plaintext), 'plaintext must be (secure) buffer')
    return Key.NONCEBYTES + plaintext.byteLength + Key.TAGBYTES
  }

  decrypt (ciphertext, buf) {
    if (this.destroyed) throw new Error('Destroyed')

    assert(Buffer.isBuffer(ciphertext), 'ciphertext must be buffer')
    const outlen = this.decryptLength(ciphertext)
    if (buf == null) buf = sodium.sodium_malloc(outlen)
    assert(buf.byteLength === outlen, 'buf must be decryptLength(ciphertext) long')

    const nonce = buf.subarray(0, Key.NONCEBYTES)
    const aead = buf.subarray(Key.NONCEBYTES)

    sodium.crypto_aead_xchacha20poly1305_ietf_decrypt(buf, null, aead, null, nonce, priv.get(this))

    return buf
  }

  decryptLength (ciphertext) {
    assert(Buffer.isBuffer(ciphertext), 'ciphertext must be buffer')
    return -Key.NONCEBYTES + ciphertext.byteLength - Key.TAGBYTES
  }

  export () {
    if (this.destroyed) throw new Error('Destroyed')
    return priv.get(this)
  }

  destroy () {
    const key = priv.get(this)
    sodium.sodium_memzero(key)
    priv.delete(key)
    this.destroyed = true
  }
}
```
