### ISSUE TITLE
Upgrading to 3.0.0

### ISSUE THREAD

**Issue by christianbundy** [holepunchto/sodium-native#120]
Hey again! :wave: 

Is there anything I need to know before upgrading to 3.0.0? My tests pass, but I'm always a bit wary of upgrading major versions before I know what the breaking change was. Thanks!

**Comment by mafintosh** [comment]
Did you see the changelog? Napi and the instance apis have been changed

**Comment by christianbundy** [comment]
I'm a bit embarrassed to admit that I didn't see that. Sorry for the noise.

> Removed object instance apis and replaced them with init, update, final methods.

:tada:

**Comment by mafintosh** [comment]
np :) let me know if it works for you. gonna be tweaking the napi version requirements over the next week so we get older version support (for free), but other than that this is a really good release
