### ISSUE TITLE
Missing functions in v3.0.0 (or documentation?)

### ISSUE THREAD

**Issue by paragonie-security** [holepunchto/sodium-native#122]
https://github.com/paragonie/sodium-plus/pull/35/checks?check_run_id=508917231

> sodium.crypto_generichash_instance is not a function

> sodium.crypto_secretstream_xchacha20poly1305_state_new is not a function

The documentation says that my usage is correct:

1. https://sodium-friends.github.io/docs/docs/generichashing - https://archive.fo/PB8Gz

2. https://sodium-friends.github.io/docs/docs/streamencryption - https://archive.fo/a4O29

The code works for 2.4.x, but not 3.x. The changelog mentions [something about init/update/final methods](https://github.com/sodium-friends/sodium-native/blob/master/CHANGELOG.md#v300), but is either misleading or leaves figuring out the expected code as an exercise to the reader.

**Comment by emilbayes** [comment]
Looks like the new docs for 3.0 didn't get merged yet: https://github.com/sodium-friends/docs/pull/4

We'll get this in order tomorrow

**Comment by emilbayes** [comment]
@paragonie-security This should be fixed now :)

EDIT: Sorry, pending publish on gh pages

**Comment by paragonie-security** [comment]
We managed to get it to build correctly: https://github.com/paragonie/sodium-plus/pull/35/commits/ceeb0c22b3511b80454aefbe91789326ca5a6f41

(Our project, sodium-plus, is a wrapper library that will use sodium-native if it's installed and fall back to libsodium.js in browsers. Best security where you can get it, without sacrificing usability.)

**Comment by emilbayes** [comment]
Sounds good, I'll close then
