### ISSUE TITLE
sodium-native/tmp/lib/libsodium.dylib'. Couldn't follow symbolic link.

### ISSUE THREAD

**Issue by suraneti** [holepunchto/sodium-native#131]
**Environment:**

**OS:** macOS Catalina 10.15.5
**Project:** React Native

Package.json (Installing with yarn)
```JSON
{
    "react": "^16.13.0",
    "react-native": "0.61.5"
}
```

Error when compiling android:
> Could not list contents of '/Users/suraneti/cto-coin/node_modules/sodium-native/tmp/lib/libsodium.dylib'. Couldn't follow symbolic link.

Solution:
Remove libsodium.dylib file then compiling successfully.

**Comment by emilbayes** [comment]
Not really sure about this, it's react native so not sure why it works in the first place

**Comment by joelfischerr** [comment]
Why is this related to react native?

I am getting the same error on macOS 11.4 when just trying to open the symbolic link in  `tmp/lib/libsodium.dylib` after building. The symbolic link seems to point to `libsodium.23.dylib` in the same directory.

Adding `rm -rf node_modules/sodium-native/tmp` does solve this issue, but I am not sure where the tmp folder is even coming from or whether it is required.
