### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by MitchellCash** [holepunchto/sodium-native#133]
When trying to use this project on macOS and Node v12.18.2 I get the following error:

`Error: No native build was found for platform=darwin arch=x64 runtime=node abi=72 uv=1 libc=glibc`

Does this project have support for macOS?

**Comment by mafintosh** [comment]
Which version of sodium-native are you using?

**Comment by MitchellCash** [comment]
@mafintosh I was using what I thought was the latest `3.2.0`, but I see that maybe this is just a pre-release version?

**Comment by mafintosh** [comment]
`3.2.0` is latest, latest macOS?

**Comment by MitchellCash** [comment]
@mafintosh yep, macOS `10.15.5`

**Comment by emilbayes** [comment]
Have you checked there are not other sodiums in your source tree? Perhaps in a nested dependency? We don’t yet have a good solution for multiple versions loaded at the same time, like you can expect from other node modules

**Comment by emilbayes** [comment]
You can check with `npm ls`

**Comment by MitchellCash** [comment]
Doesn't seem to be that either:

```
$ npm ls | grep 'sodium'
├─┬ sodium-native@3.2.0
```

I am using webpack to pack the build, could that cause an issue?

**Comment by emilbayes** [comment]
@MitchellCash That could very well be it if it messes with where the Javascript file is looking for the native module.
What is the reason you're bundling this code?

You can try adding a `console.log(__dirname)` before this line in your `node_module` or your final bundle:

https://github.com/sodium-friends/sodium-native/blob/ea065250bd5fd9f3129ae2f1c7a627248f78cd0b/index.js#L1

**Comment by MitchellCash** [comment]
Okay seems to be it was `webpack` and an issue with binary dependencies (https://jlongster.com/Backend-Apps-with-Webpack--Part-I). I have to [exclude](https://webpack.js.org/configuration/externals/) the dependencies (specifically the `sodium-native` related dependencies) in the `node_modules` folder when bundling in Webpack and _I think_ this has solved the problem so far.

In case someone gets this same issue, what I did was use the [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) package, but of course there are ways to write something yourself to exclude some or everything in `node_modules` if you don't want to use another dependency.

@emilbayes thanks for helping me debug!

**Comment by emilbayes** [comment]
Cool! Good to hear! For reference, in `browserify` it works by using `--full-paths` which replaces `__dirname` and friends with the original position the file was in. Perhaps something similar exists for webpack

**Comment by mafintosh** [comment]
Maybe we should add some of this to the docs to help other people?
