### ISSUE TITLE
Missing methods: _keygen()

### ISSUE THREAD

**Issue by christianbundy** [holepunchto/sodium-native#135]
I'm doing some mad science where I'm using libsodium.js to test (and eventually fuzz) sodium-native to ensure that everything works similarly. I've built a small adapter layer that takes the Sodium-Friends API and converts it to work with the libsodium.js API, and after a few hours of work I have adapter functions for most of the methods. I'm unfortunately missing a few:

- [ ] crypto_auth_keygen
- [ ] crypto_generichash_keygen
- [ ] crypto_secretbox_keygen

Would you accept a patch to add these three methods to Sodium-Native?

Tests I'm using are here: https://github.com/christianbundy/libsodium.js/blob/sodium-chloride/test/sodium_utils.js

The adapter that I'm building is here: https://github.com/christianbundy/libsodium.js/blob/sodium-chloride/test/sodium-chloride.js

**Comment by emilbayes** [comment]
Yep, these are all just generating random bytes based on their respective KEYBYTES constants

**Comment by emilbayes** [comment]
Ah sorry, wrong repo. But sure, expose them :)
