### ISSUE TITLE
Website shows crypto_generichash_instance, but that API was removed in v3

### ISSUE THREAD

**Issue by cakoose** [holepunchto/sodium-native#137]
The website still shows the "instance" API, `crypto_generichash_instance`: [docs](https://sodium-friends.github.io/docs/docs/generichashing#crypto_generichash_instance).

It appears that API was removed in v3: [ChangeLog link](https://github.com/sodium-friends/sodium-native/blob/master/CHANGELOG.md#v300).  Also, I tried calling it and it didn't work :-P

**Comment by mafintosh** [comment]
Yea it was removed in favour of the binary state version. Do you wanna send a PR to update docs?

**Comment by cakoose** [comment]
I'm not working with this library anymore, so I don't plan on making a PR to update the docs, sorry!
