### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by rktyt** [holepunchto/sodium-native#139]
Report from `npm audit`.

| Low | Prototype Pollution |
| --- | --- |
| Package | ini |
| Dependency of | argon2-pass  |
| Path  | argon2-pass > sodium-native > ini  |
| More info | https://npmjs.com/advisories/1589 |

**Comment by emilbayes** [comment]
We can update at next release, but we use a static ini file so this vuln is not relevant to us

**Comment by mafintosh** [comment]
Been updated
