### ISSUE TITLE
Provide Linux arm64 binaries

### ISSUE THREAD

**Issue by kesne** [holepunchto/sodium-native#147]
Right now there are no Linux arm64 builds, which makes it hard to develop on Apple silicon chips with docker. It would be ideal if binaries for Linux arm64 were prebuilt.

**Comment by Pkmmte** [comment]
It would also help those of us running on arm64 servers, such as AWS' Graviton2 instances.

**Comment by mafintosh** [comment]
There is a linux arm64 build in there now :) Let me know if it works.

**Comment by Pkmmte** [comment]
This is awesome, it worked! 

v3.3.0 was able to lower by Docker build times from 28 minutes down to only 8 minutes just like before I started using sodium-native. As far as I can tell, this new build is working perfectly! 👌 ✨

**Comment by mafintosh** [comment]
That’s awesome! Ill close this for now. If anyone has issues feel free to reopen
