### ISSUE TITLE
Test against chloride's vector tests

### ISSUE THREAD

**Issue by mafintosh** [holepunchto/sodium-native#15]
@dominictarr has a set of fixtures we should test against in https://github.com/dominictarr/chloride-test.

Since our API is different I'm thinking we can just require `chloride-test/data.json` from that repo and test against that.

**Comment by dominictarr** [comment]
I wonder if the apis follow their own conventions well enough that you could just write a very thin wrapper?

**Comment by dominictarr** [comment]
... to get from chloride to sodium-friends?

**Comment by mafintosh** [comment]
They probably do. The main difference is probably that we expect the user to allocate all return values them selves and pass them as buffers to sodium-native

**Comment by mafintosh** [comment]
They probably do. The main difference is that we expect the user to allocate all return values them selves and pass them as buffers to sodium-native.

**Comment by dominictarr** [comment]
one place where that is more complicated is on key gen, because you need to generate a pair of keys, so two return values. come to think of it, this would be more _functional_ you just generated a private key then derived a public key from it, but anyway. in those ops, the memory allocation time will not be noticable next to the cost of asymmetric crypto math. it's the symmetrical ops that really benefit from avoiding allocations.

**Comment by mafintosh** [comment]
yea agreed. the main reason we don't do any allocs here in general is just to follow the libsodium api 1-1 so we can keep this super stable and easily up to date with new sodium releases.

**Comment by mafintosh** [comment]
so there is still room to write a convenience wrapper on top of sodium-native as a separate module that makes stuff like key gen easier.

**Comment by emilbayes** [comment]
I haven't studied them too closely, but libsodium test seem to rely on a set of fixtures as defined by the `*.exp` files in the [`test/default` folder](https://github.com/jedisct1/libsodium/tree/master/test/default). Could we use them somehow?

**Comment by ralphtheninja** [comment]
> so there is still room to write a convenience wrapper on top of sodium-native as a separate module that makes stuff like key gen easier.

`chloride-native` ?

I'd _love_ to get `sodium-native` into patchwork (e.g. `ssb-keys` iirc) because it would help out a lot with install and build time.

**Comment by dominictarr** [comment]
@ralphtheninja hmm, i think the only things that use it directly are ssb-keys, private-box, pull-box-stream and secret-handshake

**Comment by dominictarr** [comment]
pull-box-stream is the only thing that would probably be measurably faster with the memory thing, so the easy way would be to just write a wrapper layer

**Comment by emilbayes** [comment]
Just for reference; we started working on out own vector tests: https://github.com/sodium-friends/sodium-test

**Comment by emilbayes** [comment]
Work continues in sodium-test so I will close this for now :)
