### ISSUE TITLE
Missing bindings for crypto_core_ed25519_scalar_mul

### ISSUE THREAD

**Issue by 0xabrarhussain** [holepunchto/sodium-native#153]
From the section https://doc.libsodium.org/advanced/point-arithmetic#scalar-arithmetic-over-l

There's the function:

```
void crypto_core_ed25519_scalar_mul(unsigned char *z, const unsigned char *x, const unsigned char *y);

The crypto_core_ed25519_scalar_mul() function stores x * y (mod L) into z.
```

Seems like sodium-native doesn't include this binding?

**Comment by mafintosh** [comment]
PR welcome! Closing for now
