### ISSUE TITLE
cannot support platform is android and arch=arm64

### ISSUE THREAD

**Issue by quwenzhe** [holepunchto/sodium-native#154]
when run in platform is android and arch=arm64, occur follow exception:

< error loading sodium bindings: No native build was found for platform=android arch=arm64 runtime=node abi=83 uv=1 armv=8 libc=glibc node=14.15.0 webpack=true

**Comment by mjovanc** [comment]
I have the same issue on Macbook M1.

**Comment by mafintosh** [comment]
@mjovanc whats your issue? you are running an android vm on mac?

**Comment by kasperisager** [comment]
This should be solved by #174 and #175.
