### ISSUE TITLE
Incorrect name function crypto_sign_seed25519_keypair in documentation

### ISSUE THREAD

**Issue by rafapaezbas** [holepunchto/sodium-native#155]
The name for sign keypair generation with seed seem to be outdated in documentation:

![screenshot](https://user-images.githubusercontent.com/15270736/151708340-63e4d45f-b548-47ee-85e1-3445275094ed.png)

The correct function name is sodium.crypto_sign_seed_keypair

**Comment by mafintosh** [comment]
PR welcome
