### ISSUE TITLE
V8_Fatal sn_crypto_aead_chacha20poly1305_ietf_decrypt

### ISSUE THREAD

**Issue by francardoso93** [holepunchto/sodium-native#158]
I'm getting this error at a running container from time to time. It forces the container to restart.

```
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffde7d04390
 1: 0xb75ed1  [node]
 2: 0x1c08724 V8_Fatal(char const*, ...) [node]
 3: 0xfcd741 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xd1ef88 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xabdab0 napi_get_typedarray_info [node]
 6: 0x7faea0479011 sn_crypto_aead_chacha20poly1305_ietf_decrypt [/app/node_modules/sodium-native/prebuilds/linux-x64/node.napi.node]
 7: 0xab44dd  [node]
 8: 0x15856cc  [node]
```

Application code: https://github.com/web3-storage/ipfs-elastic-provider-bitswap-peer/blob/main/src/noise-crypto.js
Base image: node:16
Package version: "^3.3.0"

**Comment by Powersource** [comment]
I'm getting a slighly similar error at random points in CI. Not sure if it's similar enough to maybe be the same issue but this issue was the closest I found

```
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffcfddb87f0
 1: 0xb6cab1  [node]
 2: 0x1bef8b4 V8_Fatal(char const*, ...) [node]
 3: 0xfb2ef1 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xd04968 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xab8d00 napi_get_typedarray_info [node]
 6: 0x7f4198d4462d sn_randombytes_buf [/home/runner/work/ssb-tribes2/ssb-tribes2/node_modules/.pnpm/sodium-native@3.4.1/node_modules/sodium-native/prebuilds/linux-x64/node.napi.node]
 7: 0xaaf64d  [node]
 8: 0xd3976e  [node]
 9: 0xd3ab8f v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15d55d9  [node]
Trace/breakpoint trap (core dumped)
```

https://github.com/ssbc/ssb-tribes2/actions/runs/3235493905/jobs/5300001217

Did you fix this somehow?

**Comment by Powersource** [comment]
fixed for me now by just re-running a third time :shrug:

**Comment by mixmix** [comment]
Oh hi @Powersource ... I'm getting another variant of this error too

Node 16
```
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffda067e000
 1: 0xb71fa1  [node]
 2: 0x1bf9fa4 V8_Fatal(char const*, ...) [node]
 3: 0xfb7601 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xd08ff8 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xabce40 napi_get_typedarray_info [node]
 6: 0x7f72982129ab sn_crypto_generichash [/home/mix-old/projects/AHAU/artefact-store/node_modules/sodium-native/prebuilds/linux-x64/node.napi.node]
 7: 0xab377d  [node]
 8: 0xd3ddfe  [node]
 9: 0xd3f21f v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15d9cf9  [node]
```

So that's `sodium-native@3.4.1`

What's a mystery is I'm logging around and my tests all pass when I put a console.log in logging out some result of `crypto_generichash` (the libsodium function deep in the stack). 

```js
  const hash = sodium.sodium_malloc(sodium.crypto_generichash_KEYBYTES)
  sodium.crypto_generichash(hash, msg)
  console.log(hash) // << needed T_T
```

Stabbing in the dark to try and understand what's going on found these random things which work and don't work

 works? | code 
---|---
:heavy_check_mark: | `console.log(hash)`
:x: | `console.log('dog')`
:heavy_check_mark: | `console.log(hash.slice(0,0))`
:x: | `console.log(hash.length)`

**Comment by mixmix** [comment]
Sigh ...
- node 14 : :heavy_check_mark: 
- node 16 : :x:
- node 18 : :heavy_check_mark:

**Comment by mafintosh** [comment]
Try sodium-native 4, has a series of related fixes

**Comment by mixmix** [comment]
Thanks @mafintosh
This module is used in a lot of places in our stack, it will be a bit of work to do a major version bump everywhere.

**Comment by mafintosh** [comment]
Yea, just updated a ton of modules myself. How it is sometimes 😞
