### ISSUE TITLE
Electron v 21.2.3 allocation of memory error

### ISSUE THREAD

**Issue by tmotagam** [holepunchto/sodium-native#168]
Hello,
 The latest electron 21.2.3 when sandbox mode is enabled the electron crashes with the following error

**[2356:1116/183844.292:ERROR:node_bindings.cc(146)] Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.**

when using sodium malloc to allocate safe memory buffer in nodejs

thanks

**Comment by Wolvan** [comment]
[This blog entry](https://www.electronjs.org/blog/v8-memory-cage) gives insight on what is going on here.

**Comment by tmotagam** [comment]
@Wolvan,
 Yes I know about this article but I want to allocate memory inside the ArrayBuffer of Backing Store which is not happening with the malloc of sodium native how to do that

**Comment by mafintosh** [comment]
Sounds like an electron issue, otherwise reopen
