### ISSUE TITLE
Add support for cross-compiling to Android and iOS

### ISSUE THREAD

**Issue by achou11** [holepunchto/sodium-native#171]
Trying to integrate a dep that uses `sodium-native` into a [Nodejs Mobile](https://github.com/nodejs-mobile/nodejs-mobile) + React Native project via [`nodejs-mobile-react-native`](https://github.com/nodejs-mobile/nodejs-mobile-react-native). I'm building native deps from source and having a hard time figuring out the right configuration changes needed for sodium native to work with nodejs-mobile-react-native's build steps.

Haven't gotten it to fully work but I noticed that [`sodium-native-nodejs-mobile`](https://github.com/staltz/sodium-native-nodejs-mobile) exists for this purpose. Given the existence of https://github.com/sodium-friends/sodium-native/issues/111, I was wondering if avoiding a forked module would be possible, and I have a very rough [patch file](https://github.com/digidem/react-native-with-mapeo-core-next/blob/d1a925cef84dc1160687fc0d1246f2a29d881c19/src/backend/patches/sodium-native%2B3.4.1.patch) that was basically just me trying to playing around with changes to see how it affected rebuilding (i.e. `npm rebuild --build-from-source sodium-native` targeting `arm`, `arm64`). Note that I'm more interested in getting Android to work, but iOS would also be relevant for others.

Note that this is **not** my area of expertise 😄 Figure it would be more productive to reach out and see if someone more knowledge could provide helpful input (maybe the ask is very trivial, I wouldn't know!)

(Potentially) related issues:

- https://github.com/nodejs-mobile/nodejs-mobile-module-compat/issues/5
- https://github.com/sodium-friends/sodium-native/issues/111
- https://github.com/sodium-friends/sodium-native/issues/152
- https://github.com/sodium-friends/sodium-native/issues/154

**Comment by kasperisager** [comment]
Cross-compilation support was implemented in https://github.com/sodium-friends/sodium-native/pull/174.

**Comment by kasperisager** [comment]
With #175, everything also compiles successfully on all current Android architectures.

**Comment by achou11** [comment]
@kasperisager awesome! won't be able to try it out for some time but thanks for working on this! feel free to close this issue if you want to
