### ISSUE TITLE
Compile Error In Centos7,

### ISSUE THREAD

**Issue by xinxiangwang** [holepunchto/sodium-native#176]
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@16.19.1 | linux | x64
gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.19.1/node-v16.19.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.19.1/node-v16.19.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.19.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.19.1/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/web/node_modules/sodium-native/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/web/node_modules/sodium-native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/web/node_modules/sodium-native/build'
  CC(target) Release/obj.target/sodium/binding.o
../binding.c: In function 'sn_crypto_generichash_batch':
../binding.c:454:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (uint32_t i = 0; i < batch_length; i++) {
   ^
../binding.c:454:3: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [Release/obj.target/sodium/binding.o] Error 1
make: Leaving directory `/home/web/node_modules/sodium-native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/web/node_modules/sodium-native

**Comment by mafintosh** [comment]
if still a problem on latest reopen
