### ISSUE TITLE
npm install sodium-native fails

### ISSUE THREAD

**Issue by CocolinoFan** [holepunchto/sodium-native#183]
OS: Gentoo Linux x86_64
Kernel: 6.3.9-gentoo-dist
CPU: Intel i7-7700K (8) @ 4.500GHz

I have no idea why it fails.

Log file: [2023-07-03T20_57_19_397Z-debug-0.log](https://github.com/sodium-friends/sodium-native/files/11940979/2023-07-03T20_57_19_397Z-debug-0.log)

**Comment by mafintosh** [comment]
Which version you trying to install? Your log shows you are trying to build sodium, which you are missing deps for, but it’s also showing some very old deps so mb you are building something other than latest major?

**Comment by CocolinoFan** [comment]
I don't know, I am installing some software from GitHub and one of the steps in an `npm install`. https://github.com/cjdelisle/cjdnsnode/blob/master/package-lock.json

But, turns out that I don't need that software anyway, so I don't need to install sodium-native anymore. 
Should I close the issue #183?

**Comment by mafintosh** [comment]
That's a super old version also.
