### ISSUE TITLE
Peer dependency of node-gyp-build has incorrect version

### ISSUE THREAD

**Issue by slukes** [holepunchto/sodium-native#186]
After upgrading to 4.5.0 we started experiencing these errors:

No native build was found for platform=linux arch=x64 runtime=node abi=120 uv=1 libc=glibc node=21.5.0
        loaded from: /home/runner/work/medical-data-platform/medical-data-platform/node_modules/sodium-native

    > 1 | import { crypto_aead_xchacha20poly1305_ietf_KEYBYTES, crypto_pwhash_SALTBYTES } from 'sodium-native';
    
 The fix was to pin node-gyp-build to 4.8.0

I suspect the version in your package.json does not support named prebuilds.

**Comment by mafintosh** [comment]
Dont know why you need to pin it, just latest node-gyp-build is required yea. Will force bump the semver on next release, but the current one in package.json should pick it up.
