### ISSUE TITLE
v4.2.2 linux-x64 prebuild breaks the compatibility with older intel CPUs

### ISSUE THREAD

**Issue by gholam-deblan** [holepunchto/sodium-native#204]
The new prebuild is not compatible with Intel Core i5-3570K and most probably other CPUs of the same generation.
It crashes with signal ILL:

> /node_modules/sodium-native/prebuilds/linux-x64/sodium-native.node + 0x97d7

Downgrading to 4.2.1 solves the issue.

**Comment by kasperisager** [comment]
@mafintosh It's most likely the newer processor extensions I enabled. They're supposed to be checked at runtime using CPUID as well, but I'm guessing something doesn't work as expected there.

**Comment by kasperisager** [comment]
That particular processor doesn't support AVX2.

**Comment by gholam-deblan** [comment]
It does not have AVX2, but it does have AVX and still can run a server at decent speed. Any chance this generation will still be supported in the future?

**Comment by kasperisager** [comment]
Ideally support wouldn't be affected; that certainly wasn't the intention. I'm wondering why an illegal instruction is even being executed though. If it's indeed an AVX2 instruction, I'm also wondering why the CPUID check is seemingly incorrect:

https://github.com/jedisct1/libsodium/blob/cd92e5cfc8ed53a3a8d76c2116e1b77460e88bb9/src/libsodium/sodium/runtime.c#L268-L273

If you could get some more information on exactly which instruction is causing this it'd be much appreciated! Running things through `lldb` and getting a backtrace at the faulty instruction would be a good start.

**Comment by gholam-deblan** [comment]
This is a production server I cannot really interrupt or use for any testing but I'll see if I can check anything that helps.

**Comment by kasperisager** [comment]
https://github.com/holepunchto/sodium-native/pull/206 should hopefully fix the issue. I'm still not sure why the CPUID check isn't working.

**Comment by kasperisager** [comment]
@gholam-deblan Could you try v4.3.0?

**Comment by kewlfft** [comment]
v4.3.0 fixes the problem for me, thanks
