### ISSUE TITLE
prebuild binaries error linux-arm64/sodium-native.node `GLIBC_2.33' not found 

### ISSUE THREAD

**Issue by sce9sc** [holepunchto/sodium-native#209]
I tried to install hyperdht to test it and I got the below error when starting it . 
The installation took place on an instance as below.

linux instance-20220419-1438 5.4.17-2136.306.1.3.el8uek.aarch64 #2 SMP Fri Apr 8 15:23:05 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux

node version v20.15.0
 "hyperdht": "^6.20.1"

Error: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/test/.nvm/versions/node/v20.15.0/lib/node_modules/hypertele/node_modules/sodium-native/prebuilds/linux-arm64/sodium-native.node)

**Comment by kasperisager** [comment]
Use https://github.com/holepunchto/bare-prebuild to compile prebuilds specifically for your target system.

**Comment by kasperisager** [comment]
The `linux-arm64` prebuilds are made on Ubuntu 22.04 as that's the only Ubuntu image supported by the larger hosted GitHub Actions runners: https://github.com/holepunchto/sodium-native/blob/fa392f5f53d40b9ed0d86bfde0897e3ad9cdd943/.github/workflows/prebuild.yml#L12-L14

Use https://github.com/holepunchto/bare-prebuild to compile prebuilds specifically for your target system.

**Comment by sce9sc** [comment]
So the solution is to use the below ?

npm i -g bare-prebuild
npm i sodium-native
bare-prebuild

which I tested it and it works
