### ISSUE TITLE
prebuilds for android and ios only bare No .node

### ISSUE THREAD

**Issue by sce9sc** [holepunchto/sodium-native#210]
It seems in the latest versions in some cases there are only prebuilds for bare (.bare) .

The problem is that,  since the way of how the binaries are build has changed and no longer is using node_gyp the use of bare is not always posible and thus the only way is to use prebuild . In ios and android prebuilds exist only in .bare format no .node

Thanks you.

**Comment by kasperisager** [comment]
Use https://github.com/holepunchto/bare-prebuild to compile prebuilds specifically for your target system.

**Comment by sce9sc** [comment]
How can I output .node for ios and android instead of .bare . 
Sorry for the questions but I really do not understand how. The documentation has the below flags 

```
--platform|-p <name>
--arch|-a <name>
--simulator
--debug|-d
--sanitize <name>
--define|-D <var>[:<type>]=<value>
--verbose
--help|-h
```
npm install -g bare-prebuild
bare-prebuild [flags]

I will much appreciate of any help.

**Comment by kasperisager** [comment]
Node.js doesn't support iOS so you can't create `.node` prebuilds for iOS either. To create prebuilds for Android, do:

```console
bare-prebuild -p android -a <arm|arm64|ia32|x64>
```
