### ISSUE TITLE
ios support using nodejs-mobile-react-native 

### ISSUE THREAD

**Issue by sce9sc** [holepunchto/sodium-native#211]
In the latest versions, after 4.2.0, sodium-native cannot be build by nodejs-mobile-react-native since the build process has changed. Before 4.2.0 since it was using nodegyp there was no problem.
The same applies for both Ios and android . Using 4.2.0 and up version the difference is that I can use postinstall script and create for android the necessary build using bare-prebuild which produces .node binary but for ios it does not. in only produces .bare. Do you have any ideas or point me to the right direction

**Comment by kasperisager** [comment]
Node.js doesn't support iOS and so neither will `cmake-napi` which we use for building the bindings. I can very much recommend Bare as an alternative though; it has first class support for both iOS and Android.

**Comment by sce9sc** [comment]
I would really like to use bare and the ecosystem, unfortunately looking at the documentation on how to accomplish this using the react native bare is not straightforward. There is no example of how to use the libraries apart from comminicating with bare using a script as a string. 

Thank you for your prompt reply.  I really appreciate the time
