### ISSUE TITLE
no prebuild for node 8.1.2 on linux?

### ISSUE THREAD

**Issue by dominictarr** [holepunchto/sodium-native#28]
I was surprised that npm started building sodium-native when I installed this (7.8 was fine though) how are prebuilds done and is there some way I can help ensure there are builds available for the platforms I need?

**Comment by mafintosh** [comment]
On linux 64bit? Should be a build available but maybe I'm mistaken

**Comment by dominictarr** [comment]
yeah on x64

**Comment by dominictarr** [comment]
okay, I figured out how it all works. 
```
>node -e 'console.log(process.versions.modules)'
57
```
and
```
> ls node_modules/sodium-native/prebuilds/linux-x64/
electron-47.node  electron-50.node  electron-54.node  node-14.node  node-48.node
electron-48.node  electron-51.node  libsodium.so.18   node-46.node  node-51.node
electron-49.node  electron-53.node  node-11.node      node-47.node  node-57.node
```
in fact it works. I think the problem was that when running npm rebuild
(while debugging https://github.com/ssbc/scuttlebot/issues/420) npm was just recompiling it unnecessarily.

**Comment by mafintosh** [comment]
Right, makes sense.
