### ISSUE TITLE
Undefined symbol "sodium_init"

### ISSUE THREAD

**Issue by oritwoen** [holepunchto/sodium-native#32]
Installation and build ends without errors. The error occurs after using the Dat modules via the console version of the dat and the dat-node itself.

`/usr/home/Oad/node_modules/sodium-native/build/Release/sodium.node: Undefined symbol "sodium_init"
`

Only that, nothing else is displayed.

FreeBSD 10.3-STABLE
node v4.8.2
npm  v4.0.5

**Comment by emilbayes** [comment]
FreeBSD is the only system we haven't tested ourselves as that came as a pull request. Do you know of a CI service that provides FreeBSD?

**Comment by oritwoen** [comment]
From what I know, Jenkins handles them. Unfortunately, from what I see Jenkins is a local or own server and does not make their online service such as travis.

**Comment by emilbayes** [comment]
I have a Raspberry Pi that I will flash with FreeBSD and debug

**Comment by emilbayes** [comment]
We have solved the issue, we just need to make a new release :)

**Comment by emilbayes** [comment]
@Redni Can you test again?

**Comment by emilbayes** [comment]
Closing for now. Please holla if this is still an issue and we can reopen

**Comment by oritwoen** [comment]
I'm sorry for the lack of response. Everything works, thanks! :)
