### ISSUE TITLE
Triggers recompilation on node:alpine

### ISSUE THREAD

**Issue by koistya** [holepunchto/sodium-native#33]
Is there a way to make it use precompiled binaries when installing inside a `node:alpine` Docker container? Currently, it takes a lot of time to install `sodium-native`:

```
$ docker run --rm node:8.4.0-alpine /bin/sh -c \
   "apk add --no-cache make g++ python2 && yarn add sodium-native
```

**Comment by emilbayes** [comment]
I've noticed this too. Will investigate now

**Comment by emilbayes** [comment]
Ah so this seems to be because Alpine uses musl libc. We may need to do a seperate prebuild for that, but I will need to figure out how to restructure our prebuild scripts

**Comment by koistya** [comment]
There is PR in node-sass module solving this problem, take a look.

**Comment by emilbayes** [comment]
I know this is an annoying issue, but it requires a lot of changes to our build setup and `node-build-gyp`, so unless someone wants to contribute the required changes, I will not do it this time around. Maybe in the future :)

**Comment by emilbayes** [comment]
I will close this for now. If anyone is interested and have the skills to make sodium-native work with musl, I'm more than happy to help in any way possible

**Comment by alinnow** [comment]
This is still true, so I don't really understand why the ticket was closed. It would be great to speed up CI builds for production docker containers.

**Comment by emilbayes** [comment]
@alanpearce You're welcome to submit a PR to fix this

**Comment by alinnow** [comment]
I would do so if I knew anything about native modules and their compilation, but unfortunately I don't. Having a closed issue rather suggests that there's no problem, which is not the case.
