### ISSUE TITLE
publish electron 1.8.x prebuilds (abi 57)

### ISSUE THREAD

**Issue by mmckegg** [holepunchto/sodium-native#34]
Looks like these will be included in the published module if `npm update` is run (getting the latest version of `node-abi`), and then a fresh `npm run prebuild`.

@mafintosh would you mind doing that? Thanks 😄 

Backlink: https://github.com/ssbc/patchwork/issues/597#issuecomment-333111193

**Comment by emilbayes** [comment]
We're getting ready to cut a new release with libsodium 1.0.14 out, so this shouldn't be too far off

**Comment by emilbayes** [comment]
Saturday is designated sodium-native day, but I'm having a wisdom tooth removed on friday, so let's see how it goes

**Comment by mixmix** [comment]
need this for another scuttlebutt client as well

[edit] - sorry that sounded consumerist. I love this project and it makes my life so much better everyday. The scuttlebutt community is made possible by everyones awesome work here. :revolving_hearts:

**Comment by mafintosh** [comment]
New version is most likely going out today! It'll be a major bump as there are a few minor breaking changes (the mlock apis are renamed to fit their sodium equivalent).

**Comment by mafintosh** [comment]
2.0.0 is out with support for latest electron/node. We are adding arm builds soon as well

**Comment by cryptix** [comment]
Thanks a lot!
