### ISSUE TITLE
Use sodium-native on not supported arm plaform

### ISSUE THREAD

**Issue by mseefeldt** [holepunchto/sodium-native#35]
Dear Developers,

this is not a real issue but a problem where you might help me further:

The gyp-compilation on my target platform fails due to numerous reasons
which i can not solve.
It is an ARM-based platform and coincidentally the sodium library is natively
available in the Yocto-based build system. This library can be compiled and installed
without any problems.

What changes do i have to apply to the sodium-native package to use that
pre-build lib instead of the one that gyp wants to build?

Many thanks in advance,
Marc

**Comment by emilbayes** [comment]
Prebuilds should already work on ARM per https://github.com/sodium-friends/sodium-native/pull/29

Could you provide the output where it fails and falls back to compiling?

**Comment by emilbayes** [comment]
@mseefeldt Do you have any additional information on this? We're getting ready to do a new release, and if there are any issues we would like to fix them :)

**Comment by mseefeldt** [comment]
@emilbayes 
Sorry, i was very busy the last days. The first level or error messages are like this (a lot of them, i assume that there is one for each pre-compiled library):
`ERROR: backend-1-r0 do_package: QA Issue: File '/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-arm/node-46.node' from backend was already stripped, this will prevent future debugging! [already-stripped] `

When searching on Google i found an explanation for them and i figured out how to suppress them.
They are not really important for my build.
I can suppress them and then i get to the next problem:

`
WARNING: backend-1-r0 do_package_qa: QA Issue: ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-46.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-51.node' has relocations in .text   
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-48.node' has relocations in .text   
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/electron-49.node' has relocations in .text   
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/electron-48.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/electron-54.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/electron-51.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/electron-50.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/electron-47.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-14.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/electron-53.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-47.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-57.node' has relocations in .text
`
`
ELF binary '/opt/yocto/build/tmp/work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-11.node' has relocations in .text [textrel]
`

In addition i get the following errors (i only selected one for each architecture):
`
ERROR: backend-1-r0 do_package_qa: QA Issue: Architecture did not match (40 to 183) on work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-arm64/node-46.node
`
`
Architecture did not match (40 to 3) on work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-ia32/node-46.node
`
`
Architecture did not match (40 to 62) on work/cortexa8hf-neon-phytec-linux-gnueabi/backend/1-r0/packages-split/backend/var/www/backend/backend/node_modules/sodium-native/prebuilds/linux-x64/node-46.node
`

The board i am developing for is phyCORE AM335x board.
Here is the result for uname -a
`
Linux phycore-am335x-7 4.4.19-AM335x-PD16.2.0 #1 Tue Sep 26 15:26:29 CEST 2017 armv7l GNU/Linux`

The build system is a Yocto-based system using the cross compiler *arm-phytec-linux-gnueabi* with the  flags
`
TUNE_FEATURES     = "arm armv7a vfp thumb neon       callconvention-hard       cortexa8"      
`
`
TARGET_FPU        = "hard"
`

If the analysis of this issue takes too long, i can also live with instructions to use the native libsodium for the project and replace the precompiled lib with that one. Would it be as simple as copying the library into the deps folder?
Many thanks in advance for your support!

**Comment by emilbayes** [comment]
You original question is how to have sodium-native use your global installation of libsodium which is not something we will support. I think you may be able to do it by skipping our `npm install` script and running `node-gyp build` in the project. It will use the header files in our libsodium submodule, but should pick up your global installation of libsodium. You may be able to check `ldd build/Release/sodium.node` and see that it picks up your libsodium. But again, I'm just guessing
