### ISSUE TITLE
secretstream API?

### ISSUE THREAD

**Issue by jedisct1** [holepunchto/sodium-native#39]
Hi,

And congrats for the release of sodium-native 2.0!

It's pretty lame to open a ticket for a feature request, but I don't have much experience with writing native modules.

If this is out of the scope of the features set planned for sodium-native, feel free to close this ticket right away.

Anyway, it would be fantastic if sodium-native had wrappers for the secretstream API. This API is present in libsodium.js so having it in sodium-native to receive the streams would be convenient.

**Comment by mafintosh** [comment]
The next release will have secretstream. We just wanted to get the updated libsodium out first :)

**Comment by jedisct1** [comment]
\o/

**Comment by emilbayes** [comment]
We were a bit stressed with our crypto workshop, but I already have the tests in place for secret stream, just need to expose it and do some more verification!

**Comment by emilbayes** [comment]
@jedisct1: https://github.com/sodium-friends/sodium-native/pull/46
