### ISSUE TITLE
Missing constant: crypto_pwhash_ALG_ARGON2ID13

### ISSUE THREAD

**Issue by vladimiry** [holepunchto/sodium-native#41]
Partial constants values dump:
```
...
  crypto_pwhash_OPSLIMIT_MIN: 1,
  crypto_pwhash_OPSLIMIT_MAX: 4294967295,
  crypto_pwhash_MEMLIMIT_MIN: 8192,
  crypto_pwhash_MEMLIMIT_MAX: 4398046510080,
  crypto_pwhash_OPSLIMIT_INTERACTIVE: 2,
  crypto_pwhash_MEMLIMIT_INTERACTIVE: 67108864,
  crypto_pwhash_OPSLIMIT_MODERATE: 3,
  crypto_pwhash_MEMLIMIT_MODERATE: 268435456,
  crypto_pwhash_OPSLIMIT_SENSITIVE: 4,
  crypto_pwhash_MEMLIMIT_SENSITIVE: 1073741824,
...
```

Error received on `sodium.crypto_pwhash_async` call with `opsLimit` set to `crypto_pwhash_OPSLIMIT_MIN` (1) / `crypto_pwhash_OPSLIMIT_INTERACTIVE` (2):
```
message: EINVAL, Invalid argument, errno: 22, code: "EINVAL"
```

Related [documentation quote](https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html): 
```
opslimit, the number of passes, has to be at least 3 when using Argon2i. crypto_pwhash() and crypto_pwhash_str() will fail with a -1 return code for lower values.
```

Versions used:
- sodium-native: 2.0.0
- node -v: v8.8.1
- npm -v: 5.5.1
- OS: linux414-x86_64

Might be related issue https://github.com/jedisct1/libsodium.js/issues/119 Based on this issue sodium-native 1.10.3 had correct `crypto_pwhash_OPSLIMIT_*` values - 3 and up.

**Comment by emilbayes** [comment]
@vladimiry Which value are you using for the `alg` param? `crypto_pwhash_OPSLIMIT_MIN` for Argon2i should be `3`, but since that is no longer the default algorithm in libsodium 1.0.15, and since sodium-native 2.0.0, I guess the min. number of passes is now `1` for Argon2id (which is the default now)?

Relevant code snippets:

https://github.com/jedisct1/libsodium/blob/c5e43f4c1cf62b4669b1f33516fc33ef2d005187/src/libsodium/include/sodium/crypto_pwhash.h#L25

https://github.com/jedisct1/libsodium/blob/c5e43f4c1cf62b4669b1f33516fc33ef2d005187/src/libsodium/include/sodium/crypto_pwhash.h#L57

https://github.com/jedisct1/libsodium/blob/c5e43f4c1cf62b4669b1f33516fc33ef2d005187/src/libsodium/include/sodium/crypto_pwhash_argon2id.h#L49

**Comment by emilbayes** [comment]
It also looks like those parts of the documentation might need some updating

**Comment by vladimiry** [comment]
sodium-native: 2.0.0 has only these `crypto_pwhash_ALG_*` constants exposed:
```
  crypto_pwhash_ALG_ARGON2I13: 1,
  crypto_pwhash_ALG_DEFAULT: 2,
```
So no explicitly defined crypto_pwhash_ALG_ARGON2ID13, and crypto_pwhash_ALG_DEFAULT is set to 2, which is probably the crypto_pwhash_ALG_ARGON2ID13 value. It looks a little weird to me that there is crypto_pwhash_ALG_DEFAULT set to 2 without respective value=2 constant defined. I'm referencing crypto_pwhash_ALG_ARGON2I13 as the `alg` param and thus I run into the described issue.

I've got it that it's safer to use crypto_pwhash_ALG_DEFAULT, not the specific ALG constant value directly, since related crypto_pwhash_OPSLIMIT_* / crypto_pwhash_MEMLIMIT_* constants are defined to work well with the crypto_pwhash_ALG_DEFAULT algorithm only.

I confirm that it works well with "opsLimit":3 (crypto_pwhash_OPSLIMIT_INTERACTIVE) and "algorithm":2 (crypto_pwhash_ALG_DEFAULT) values set. So the only issue is the absence of the crypto_pwhash_ALG_ARGON2ID13=2 constant.

**Comment by emilbayes** [comment]
Ah yes, that is one of the many symbols we're missing. The list of all the symbols we should expose is available here: https://github.com/sodium-friends/sodium-test/blob/master/documented-symbols

PR's are very welcome! :)

**Comment by emilbayes** [comment]
So just for posterity, the following works (using the "hidden" Argon2id alg and `OPSLIMIT === 1`):

```js
var sodium = require('sodium-native')

var hash = Buffer.alloc(64)
var password = Buffer.from('secret')
var salt = Buffer.alloc(sodium.crypto_pwhash_SALTBYTES)

sodium.randombytes_buf(salt)

console.log(sodium.crypto_pwhash_OPSLIMIT_MIN,
sodium.crypto_pwhash_MEMLIMIT_MIN,
sodium.crypto_pwhash_ALG_DEFAULT) // 1 8192 2

sodium.crypto_pwhash(hash, password, salt,
  sodium.crypto_pwhash_OPSLIMIT_MIN,
  sodium.crypto_pwhash_MEMLIMIT_MIN,
  sodium.crypto_pwhash_ALG_DEFAULT
)
```

**Comment by emilbayes** [comment]
I have updated the title accordingly :)

**Comment by vladimiry** [comment]
Thanks Emil! And I'd also highlight for posterity this sentence:

`
it's safer to use crypto_pwhash_ALG_DEFAULT, not the specific ALG constant value directly, since related crypto_pwhash_OPSLIMIT_* / crypto_pwhash_MEMLIMIT_* constants are defined to work well with the crypto_pwhash_ALG_DEFAULT algorithm only.
`

Means if someone doing new keys deriving (it affects only the new keys deriving scenario, as re-deriving normally happens using the saved parameters) does call `sodium.crypto_pwhash / sodium.crypto_pwhash_async` relying on the `crypto_pwhash_*` constants then it's safe to use only the `crypto_pwhash_ALG_DEFAULT` value in combination with other `crypto_pwhash_*` constants, not the explicit algorithms constants as there is no valid constants sets defined for each algorithm (which might be a good idea), but only for the `crypto_pwhash_ALG_DEFAULT`.

**Comment by vladimiry** [comment]
This list https://github.com/sodium-friends/sodium-test/blob/master/documented-symbols exposes 299 symbols, while `sodium-native` exposes only 127 symbols (minus 3 `*_async` symbols, which makes it 124). Do I get it right that generally it's not only the `crypto_pwhash_ALG_ARGON2ID13` is missed ? :)

[documented-symbols .txt](https://github.com/sodium-friends/sodium-native/files/1466338/documented-symbols.txt)
[sodium-native-symbols.txt](https://github.com/sodium-friends/sodium-native/files/1466339/sodium-native-symbols.txt)

**Comment by mafintosh** [comment]
You can send a PR for any missing symbols, and it'll be out in the next release.

**Comment by emilbayes** [comment]
@vladimiry The script for doing that comparison is already in sodium-test, but needs to become part of the automated testing: https://github.com/sodium-friends/sodium-test/blob/master/compare-symbols.sh

As said previously, you're welcome to add any symbols. We should create a contributors guide, but time has not allowed itself yet. So for now, what is required is test vectors, good and bad input tests and of course exposing appropriate symbols and docs :)

**Comment by vladimiry** [comment]
So the ultimate idea would be in adding test like shown below to the `sodium-test` suite and then integrating running all the tests defined in `sodium-test` into the new `sodium-native` release producing process?
```javascript
const fs = require('fs');
const path = require('path');
const readline = require('readline');
const test = require('tape');

module.exports = (sodium) => {
    test('compare-symbols', (assert) => {
        assert.plan(1);

        const expectedSymbols = [];

        readline
            .createInterface({
                input: fs.createReadStream(path.join(__dirname, 'documented-symbols')),
            })
            .on('line', (line) => {
                if (!line.startsWith('#') && line.trim()) {
                    expectedSymbols.push(line.trim());
                }
            })
            .on('close', () => {
                const sodiumSymbols = Object.keys(sodium);

                expectedSymbols.sort();
                sodiumSymbols.sort();

                assert.deepEqual(sodiumSymbols, expectedSymbols, 'matching "documented-symbols" and "sodium" symbols');
            });
    })
}
```

Is the `sodium-test` tests running currently integrated into the `sodium-native` release process? If it's not, then seems I better put it into the application tests, just like this:
```typescript
import * as sodium from "sodium-native";
import * as sodiumTest from "sodium-test";

sodiumTest(sodium);
```

Regarding creating PR. I think I can try to add crypto_pwhash_ALG_ARGON2ID13 to handle this specific issue and to get familiar with the process in general. But I'm not familiar with the specifics of other missed symbols usage, as well as I'm not into the C++ coding.

**Comment by emilbayes** [comment]
The sodium-test repo is shared by sodium-native and sodium-javascript, which is why it is nice to have visibility into which symbols are implemented across the two, as well as for tracking which symbols developers expect from reading the libsodium docs. There's nothing official about the symbol list, it's simply what I have created by hand from skimming the libsodium docs and noting down all the mention functions and constants.

**Comment by emilbayes** [comment]
Exposed now and added test cases for all pwhash const to prevent this happening again :)

Not released yet tho
