### ISSUE TITLE
Support for AEAD Constructions?

### ISSUE THREAD

**Issue by tomekmarchi** [holepunchto/sodium-native#47]
With TLS 1.3 dropping many ciphers but adopting a good portion of AEADs like ChaCha. Are there any plans to include crypto_aead_xchacha20poly1305_ietf_encrypt? Are any currently supported?

**Comment by emilbayes** [comment]
@tomekmarchi I'm currently adding secretstream which is built on `crypto_aead_xchacha20poly1305_ietf`. PR's are welcome as long as they have good tests (I usually port the ones from libsodium itself)

**Comment by tomekmarchi** [comment]
@emilbayes Dear Lord of Lords, are you saying that when your work on secretstream is done the crypto_aead_xchacha20poly1305_ietf API will be exposed? Bless your soul kind sir.

**Comment by emilbayes** [comment]
Work on this has begun in #62

**Comment by tomekmarchi** [comment]
@emilbayes This is a blessed day. Thank, be the crypto Gods and baes of baes!

**Comment by emilbayes** [comment]
Now XChaCha20/Poly1305 is exposed! More will follow in subsequent releases :)
