### ISSUE TITLE
Empty secretstream header

### ISSUE THREAD

**Issue by letalumil** [holepunchto/sodium-native#61]
`crypto_secretstream_xchacha20poly1305_init_push` doesn't set header value and the buffer is filled with zeros. I debugged corresponding [libsodium test case](https://github.com/jedisct1/libsodium/blob/b3ffad36483939fd627f4c5363f8f55d313dd387/test/default/secretstream.c#L66) and everything seems to be fine there, the value is lost somewhere in between.

I added an assertion to reproduce the problem, not the fanciest one, but should help at least :)

**Comment by jedisct1** [comment]
Ouch. If the IV is constant, this is a pretty serious vulnerability.

**Comment by emilbayes** [comment]
I see more mistakes. On it now

**Comment by emilbayes** [comment]
Building now and a new release will be out in a few hours

**Comment by emilbayes** [comment]
@letalumil Thank you very much for reporting this! It is released as `2.1.5`
