### ISSUE TITLE
Prebuilds for Node 10

### ISSUE THREAD

**Issue by emilbayes** [holepunchto/sodium-native#65]
Working on this

**Comment by fczuardi** [comment]
is arm64 a target? maybe I can help with that if needed :)

**Comment by emilbayes** [comment]
@fczuardi The armv7l builds don't work for you?

**Comment by fczuardi** [comment]
npm i sodium-native triggered a compilation here, so maybe not

**Comment by emilbayes** [comment]
Do you know of anywhere we can get arm64 machines to do the builds automatically? Right now it is all built on Appveyor and Travis CI, except for armv7l which I build by hand :)

**Comment by fczuardi** [comment]
I have one at home (rock64), but I can look for commercial cloud or CI services for it too, maybe https://www.scaleway.com/ ?

**Comment by mafintosh** [comment]
@emilbayes i've used https://www.scaleway.com/ in the past
