### ISSUE TITLE
Module version 64 prebuilds for electron v3

### ISSUE THREAD

**Issue by vladimiry** [holepunchto/sodium-native#69]
This is a feature request. Electron [v3.0.0-beta.1](https://github.com/electron/electron/releases/tag/v3.0.0-beta.1) just got released.

**Comment by emilbayes** [comment]
Thanks for letting us know! I guess the ABI is stable despite it being a beta, so I will try and run a build

**Comment by emilbayes** [comment]
This version did not make the latest release as it is still marked as "future" in `node-abi`: https://github.com/lgeiger/node-abi/blob/dd887dac18822e6522187ab412821f120eb59730/index.js#L95-L97

It will be included as soon as it transitions into `supportedTargets`, and I'm happy to do a build then :)

**Comment by vladimiry** [comment]
Hi @emilbayes, electron 3.0.0 is now specified in the `supportedTargets` section.

**Comment by emilbayes** [comment]
@vladimiry I will do a new build as soon as I have time (today or tomorrow)

**Comment by vladimiry** [comment]
Great! Can the issue be reopened then, until resolved :)

**Comment by emilbayes** [comment]
@vladimiry Finally got around to it. Currently waiting for artefacts :)

**Comment by vladimiry** [comment]
Thanks! Going to try v2.2.2 with Electron v3 once it's published. Will confirm then that it works as expected.

**Comment by emilbayes** [comment]
@vladimiry Out now :)

**Comment by vladimiry** [comment]
I confirm v2.2.2 works nicely with Electron v3.
