### ISSUE TITLE
Maximum buffer lengths

### ISSUE THREAD

**Issue by jackschmidt** [holepunchto/sodium-native#73]
While libsodium provides some maximum buffer sizes, most are quite large and unlikely to be reached in node. However, a few of the limits are real. Here is a weird error message when asking for a hash size larger than the maximum (65 vs 64). Notice the too small error message is quite informative, while the too big error message is ", Success".

    const sodium = require('sodium-native');
    const output_justright = Buffer.alloc( sodium.crypto_generichash_BYTES_MAX );
    const output_toosmall = Buffer.alloc( sodium.crypto_generichash_BYTES_MIN - 1);
    const output_toobig = Buffer.alloc( sodium.crypto_generichash_BYTES_MAX + 1 );
    const message = Buffer.alloc( 17 );
    sodium.crypto_generichash( output_justright, message );
    sodium.crypto_generichash( output_toosmall, message );

    Error: output must be a buffer of size crypto_generichash_BYTES_MIN

    sodium.crypto_generichash( output_toobig, message );
    
    Error: , Success

Would it be reasonable to add some ASSERT_UINT_BOUNDS in a variation of ASSERT_BUFFER_MIN_LENGTH? Perhaps ASSERT_BUFFER_LENGTH_BOUNDS?

**Comment by emilbayes** [comment]
You are right something is wrong here. I will look into the issue. The `, Success` error message is something I have been working on making better for a while, so this is another push to finish that off

**Comment by emilbayes** [comment]
This should now be solved in the N-API version
