### ISSUE TITLE
Prebuilds for node 11 on Ubuntu 64-bit x86

### ISSUE THREAD

**Issue by emilbayes** [holepunchto/sodium-native#77]
@ralphtheninja notified me that prebuilds don't seem to work for the target we call linux-x86_64 with node 11 (and possibly older versions)

**Comment by mafintosh** [comment]
People at the workshop were having issues with this as well at Coldfront

**Comment by ralphtheninja** [comment]
Just some more info:

```sh
$ node -p process.versions
{ http_parser: '2.8.0',
  node: '11.3.0',
  v8: '7.0.276.38-node.11',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '63.1',
  unicode: '11.0',
  cldr: '34.0',
  tz: '2018e' }
```

And in a installed version of `sodium-native@2.2.3`:

```
$ l prebuilds/linux-x64/
total 3,4M
drwxr-xr-x 2 lms lms 4,0K nov 28 13:57 .
drwxr-xr-x 7 lms lms 4,0K nov 28 13:57 ..
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-47.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-48.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-49.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-50.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-51.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-53.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-54.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-57.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 electron-64.node
-rwxr-xr-x 1 lms lms 331K okt 26  1985 libsodium.so.23
-rwxr-xr-x 1 lms lms 205K okt 26  1985 node-47.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 node-48.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 node-51.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 node-57.node
-rwxr-xr-x 1 lms lms 205K okt 26  1985 node-59.node
-rwxr-xr-x 1 lms lms 209K okt 26  1985 node-64.node
```

It seems it's missing prebuilts for abi 67 (which corresponds to node v11). Older versions are ok though.

**Comment by emilbayes** [comment]
I just checked and none of the CI builds have 67 for some reason, while our hand built armv7l builds have this

**Comment by ralphtheninja** [comment]
> I just checked and none of the CI builds have 67 for some reason, while our hand built armv7l builds have this

Maybe add a step that lists the resulting `prebuilds` folder as well. Makes it easier to check later.

**Comment by emilbayes** [comment]
Just restarted the builds to see what is happening. Yeah that's a good idea! I normally inspect the `npm pack` tarball before publishing to make sure, but mustn't have been thorougher enough this time

**Comment by ralphtheninja** [comment]
Hmm, I'm wondering if it can be some sort of race condition. I don't see exactly how the `tar` command works with multiple node versions (i.e. the `before_deploy` step in Travis).

**Comment by emilbayes** [comment]
These guard against that:

https://github.com/sodium-friends/sodium-native/blob/5baff816030bc327a4aa141275041fbecd961993/.travis.yml#L43-L45

https://github.com/sodium-friends/sodium-native/blob/5baff816030bc327a4aa141275041fbecd961993/appveyor.yml#L47-L49

**Comment by ralphtheninja** [comment]
Oh right, so on the `node` node, this is the only one that does `prebuildify -a ..` etc. I get it now. So no race condition is possible. What if e.g. `node-abi` was outdated at the time or something like that?

**Comment by emilbayes** [comment]
Yeah that's what I'm thinking is causing it. Let's see when the builds complete in a little while

**Comment by emilbayes** [comment]
Checking now that was exactly the issue. I will issue a new release.
Thanks for the help!

**Comment by ralphtheninja** [comment]
> Thanks for the help!

No worries! Don't forget to close this :wink:

**Comment by emilbayes** [comment]
I made this repo to avoid this happening in the future: https://github.com/sodium-friends/sodium-native-citgm
