### ISSUE TITLE
Provide hash reset() functions, so we can reuse state and avoid allocating.

### ISSUE THREAD

**Issue by cakoose** [holepunchto/sodium-native#84]
This package generally lets you provide a pre-allocated output buffer, which lets me avoid an allocation.

But for hashing a stream of buffers, every time I want to hash something I need to call a function that allocates e.g. `crypto_hash_sha512_instance()`.  It would be nice if I could pre-allocate that as well.

One option: an `instance.reset()` method that resets the state.  That way I can allocate a single instance and use it to hash many things.

(Calling it `instance.init()` would work too, though people might think it's required to call `init()` before using it the first time.)

**Comment by emilbayes** [comment]
This will be fixed when we land this PR: https://github.com/sodium-friends/sodium-native/pull/55

Then there are no longer any object wrappers, but state is stored in a buffer that you explicitly pass to `init`/`update`/`final` and you can do whatever you want :)

**Comment by cakoose** [comment]
Sounds good!
