### ISSUE TITLE
Use more strict dependencies' versions

### ISSUE THREAD

**Issue by diego-G** [holepunchto/sodium-native#85]
Right now, you are using caret `^` which is too broad for a critical library like yours.

We will appreciate if you freeze your dependencies or at least, use tilde `~` instead of caret.

https://github.com/sodium-friends/sodium-native/blob/43d8f8dd2cbce0760902e30296ed9eebd560a81e/package.json#L6

**Comment by emilbayes** [comment]
Hi! I understand your sentiment but this will not prevent those dependencies from having more relaxed semver selectors. The only practical solution to mitigate this is to have a lock file
