### ISSUE TITLE
Electron 4: broken brebuilds due to ABI incompatibilities

### ISSUE THREAD

**Issue by vladimiry** [holepunchto/sodium-native#90]
Can a similar https://github.com/atom/node-keytar/issues/133#issuecomment-460630739 fix be applied here? As currently I have to recompile the stuff. See this PR https://github.com/atom/node-keytar/pull/157.

**Comment by emilbayes** [comment]
We are using `sodium-native@2.2.6` with `electron@4.0.4` without recompiling. It was released yesterday due to the ABI issue that was caused by electron

**Comment by vladimiry** [comment]
My bad, I see this issue has been handled already with recently published v2.2.6 release :+1:
