### ISSUE TITLE
crypto_sign_ed25519_sk_to_pk

### ISSUE THREAD

**Issue by mjp0** [holepunchto/sodium-native#91]
I noticed that `crypto_sign_ed25519_sk_to_pk` method is missing. It's being talked about here: https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures#extracting-the-seed-and-the-public-key-from-the-secret-key

I don't have any experience with writing nodejs bindings so I've no idea how big of a job it would be to include this method also but I really hope it's not because I could really use this method.

**Comment by emilbayes** [comment]
This will be in the next release :)
