### ISSUE TITLE
undefined symbol: crypto_core_ed25519_scalarbytes

### ISSUE THREAD

**Issue by jfr3000** [holepunchto/sodium-native#93]
This happens using the linux-x64/node-67.node prebuild. 2.2.6 works for me, so I guess this was introduced very recently? Any suggestions?

**Comment by emilbayes** [comment]
Hmm, this is strange. Our canary setup has not reported any errors and we cannot reproduce: https://travis-ci.org/sodium-friends/sodium-native-citgm/jobs/494464274

Are we correct in assuming you're using latest Node (11.x)? That's what I guessed from node-67 (ABI 67)

**Comment by mafintosh** [comment]
Also can you share the output of `ldd node-67.node` ?

**Comment by jfr3000** [comment]
Yes, I'm using 11.9 but I tried different node versions, and the result was the same :(

```
ldd ./node_modules/sodium-native/prebuilds/linux-x64/node-67.node
	linux-vdso.so.1 =>  (0x00007ffc8adf7000)
	libsodium.so.23 => ./node_modules/sodium-native/prebuilds/linux-x64/libsodium.so.23 (0x00007f47c9075000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f47c8cf3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f47c8ad6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f47c870c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f47c9502000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f47c8403000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f47c81ed000)
```

**Comment by emilbayes** [comment]
@jfr3000 It all seems normal to me. You can try going to the `sodium-native` directory in our `node_modules` and run `npm install` from there. That should recompile in your case, but I just want to see what happens.

**Comment by jfr3000** [comment]
Did that, and same result :woman_shrugging: @regular is having the same issue on his machine. Guess I'll stick with the workaround for now...

**Comment by christianbundy** [comment]
I can also reproduce this with Electron 2 (ABI 57, same as Node 8.0.0). Here's what I'm seeing:

```
/home/christianbundy/src/ssbc/patchwork/node_modules/electron/dist/electron --type=renderer --no-sandbox --service-pipe-token=CC461C4E397CF030BCCB2A569F3C27AD --lang=en-US --app-path=/home/christianbundy/src/ssbc/patchwork/node_modules/electron/dist/resources/default_app.asar --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --context-id=2 --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;0,17,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;1,17,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;2,17,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;3,17,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553;4,17,3553 --disable-accelerated-video-decode --enable-gpu-async-worker-context --service-request-channel-token=CC461C4E397CF030BCCB2A569F3C27AD --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101: symbol lookup error: /home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/sodium-native/prebuilds/linux-x64/electron-57.node: undefined symbol: crypto_core_ed25519_scalarbytes
```

**Comment by emilbayes** [comment]
@christianbundy can you please run lld like above and report back? Also OS details would be helpful. We have a canary that test every night and have done extensive manual testing (we’re working on an electron app on macOS and Linux) and have not had these issues, so we suspect that something is wrong with your dynamic linker perhaps

**Comment by christianbundy** [comment]
Sorry for the noise, I've tried reinstalling with `npm install` and now it seems to work. I'm not sure what was going on but it's gone now. Maybe my machine is haunted?

**Comment by regular** [comment]
@christianbundy you machine is probably alright. I am having this problem since a month or so, on both Linux and OSX. It happens so often that I've learned to live with it and my zsh autocompletes `npm i s` to `npm i sodium-native@2.2.6`

**Comment by mafintosh** [comment]
@regular we have a hard time reproducing, does this happen to you regularly with 2.3.0?

**Comment by emilbayes** [comment]
@regular Can you please provide details of your OS and the ldd output so we can debug further?

**Comment by emilbayes** [comment]
@regular @jfr3000 Are you running sodium-native through electron? Just fell over this: https://github.com/electron-userland/electron-builder/issues/3590

**Comment by emilbayes** [comment]
I know what is going on now thanks to @andrewosh. Two different versions of libsodium are trying to be loaded, both compatible but one has a few more features than the other. It is something I've been working on for a while but never saw having practical relevance. Will try to come up with a fix for the new release

**Comment by mixmix** [comment]
_Oh look, a scuttlebutt party._

I'm hitting this bug with `electron-builder` (this branch of [patchbay](https://github.com/ssbc/patchbay/pull/333)). What I'm seeing is that `npm start` works, but when I try to build a release I get this error.
Messed with build config (made it more wasteful, less fancy) and now I'm not getting misaligned libsodium

**Comment by emilbayes** [comment]
@mixmix `electron-builder`s rebuild logic seems broken :( We've had to introduce a flag to disable the prebuilding logic for `node-gyp-build`: https://github.com/prebuild/node-gyp-build/commit/05d27cb68b5fdb3bc126e6c3f756c41b4eff7fc4

The above fix I thought I'd found, I couldn't get to reproduce. I have the test case here: https://github.com/emilbayes/sodium-symbol-bug. Maybe someone could provide a complete `tree` of what the final electron app looks like (including the asar bundle) so I can see if competing versions of `sodium-native` is actually the cause. A `package-lock.json` file from a bugged build may also work

**Comment by vweevers** [comment]
Here's a repro that works on (at least) ubuntu and windows: https://github.com/vweevers/sodium-symbol-bug/tree/npm-aliases.

What may help (probably not for this specific issue but you should do it anyway for mac), is adding the following to `binding.gyp`:

```
["OS == 'mac'", {
   "cflags+": ["-fvisibility=hidden"],
   "xcode_settings": {
     "GCC_SYMBOLS_PRIVATE_EXTERN": "YES" # -fvisibility=hidden
   }
}]
```

To make symbols hidden. Because the problem is, on mac, `dlopen()` defaults to `RTLD_GLOBAL`, which means if the node addon has any global symbols, they will be exported, causing conflicts if you then load another addon that has symbols with the same names.

See also https://github.com/nodejs/node-gyp/pull/1891 and https://github.com/vweevers/about-native-modules

**Comment by vweevers** [comment]
Update: doesn't happen on mac, only ubuntu and windows. And only when using prebuilt binaries. [Here's an alternative way to reproduce](https://github.com/vweevers/about-native-modules/#2019-11-03-sodium-native), that runs the tests of `sodium-native`. Its output shows which versions can't be loaded into the same process:

|         | `2.4.6` | `2.4.2` | `2.3.0` | `2.2.6` | `2.2.5` |
| --------| ------- | ------- | ------- | ------- | ------- |
| `2.4.6` | -       | OK      | OK      | ERR     | ERR     |
| `2.4.2` | OK      | -       | OK      | ERR     | ERR     |
| `2.3.0` | OK      | OK      | -       | ERR     | ERR     |
| `2.2.6` | OK      | OK      | OK      | -       | OK      |
| `2.2.5` | OK      | OK      | OK      | OK      | -       |

**Comment by mafintosh** [comment]
I think this is fixed, if not reopen

**Comment by tacerus** [comment]
Hi! Could you link the commit or PR fixing this? I only notice #1046 mentioned, but that one was closed with no merge.
